name: Ansible Lint

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/ansible/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/ansible/**'

jobs:
  lint:
    name: Lint Ansible Playbooks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint
      
      - name: Run ansible-lint
        run: |
          cd src/ansible
          ansible-lint playbooks/*.yml

